name: Start index.js file.
on: push
jobs:
  run-index:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Run index
        run: npm run start
